name: build

on: [push]

jobs:
  deploy-on-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Preparing deploy ⚙️
        run: mkdir -p public/ && mv -t public/ index.html
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/
